### ISSUE TITLE
Bitte Vorgehen erläutern 

### ISSUE THREAD

**Issue by ghost** [ADFC-Hamburg/adfc-t30-paten-map#1]
Lieber Sven, 

cool!!! Danke für deine Arbeit! 

Bevor ich konkrete Rückmeldungen gebe, bräuchte ich glaube ich eine Erklärung wie du vorgegangen bist. 

Wie kommt die Verteilung der Farben auf die Einrichtungen zustande? 
Hast du Rikes Datei mit den korrigierten Geo-Daten als Grundlage genommen? 
Sind die Beschreibungen in den Feldern bei "Stand der Dinge" erst mal nur Dummies? Denn bei gelb, grün und orange passen sie nicht zu der Legende, die ich dir geschickt habe. 
Die Auswahl bei blau und rot finde ich sehr cool. Wie geht es nach den grünen Auswahlfeldern denn weiter? 

Konrete Rückmeldungen gebe ich dann in neuen Issues. 
Danke und LG, Wiebke

**Comment by tabacha** [comment]
Farben sind Zufall. Sollten sich auch bei jedem laden der Seite anders sein. Da ja ansonsten alles am Anfang Blau wäre.

Ich habe die Daten von Rike genommen.

Bei den Farben muss ich noch mal schauen, eigentlich sollten das die Farben aus der Vorgabe sein.

Wie es nach Click dann weitergeht können wir dann noch genau schauen. Wahrscheinlich landet man auf der Login-Registrieren Seite und dann auf einer entsprechend vorausgefüllten weiteren Seite.

**Comment by tabacha** [comment]
Farben sind hier definiert:

https://github.com/ADFC-Hamburg/adfc-t30-paten-map/blob/8615426c2059070775bd73d99c1cf6c7ac16c576/layer/soz-einrichtung.ts#L12

Die Texte dazu zwei Zeilen tiefer als POPUP_TEXT Wobei die erste Farbe zum ersten Text passen sollte usw.

https://github.com/ADFC-Hamburg/adfc-t30-paten-map/blob/8615426c2059070775bd73d99c1cf6c7ac16c576/layer/soz-einrichtung.ts#L14-L18

**Comment by ghost** [comment]
Danke, wie schließt man eigentlich ein Issue?

**Comment by tabacha** [comment]
Unten auf den Button "Close Issue" oder (wenn du einen Kommentar eingeben hast) "Close and comment" clicken
